# Generated by Django 4.2.9 on 2024-02-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kml_file', models.CharField(max_length=255)),
                ('tiff_file', models.CharField(max_length=255)),
                ('ndvi_file', models.CharField(max_length=255)),
                ('stats', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shp',
            name='file',
            field=models.FileField(upload_to='shps/%Y/%m/%d'),
        ),
    ]
