# Generated by Django 4.2.9 on 2024-02-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0002_geodata_alter_shp_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geodata',
            old_name='kml_file',
            new_name='kml_file_key',
        ),
        migrations.RenameField(
            model_name='geodata',
            old_name='ndvi_file',
            new_name='ndvi_file_key',
        ),
        migrations.RenameField(
            model_name='geodata',
            old_name='tiff_file',
            new_name='tiff_file_key',
        ),
    ]
