# Generated by Django 4.2.9 on 2024-02-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0003_rename_kml_file_geodata_kml_file_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodata',
            name='kml_file_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='ndvi_file_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='stats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='tiff_file_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
