# Generated by Django 4.2.9 on 2024-01-27 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiff", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiff",
            name="file",
            field=models.FileField(upload_to="tiffs/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="tiff",
            name="uploaded_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
