# Generated by Django 4.2.9 on 2024-02-19 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiff', '0002_alter_tiff_file_alter_tiff_uploaded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiff',
            name='uploaded_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
