# Generated by Django 4.2.9 on 2024-03-04 13:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiff', '0005_alter_tiff_uploaded_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiffLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='tiff',
            name='uploaded_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='geopoint',
            name='tiff_layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='tiff.tifflayer'),
        ),
    ]
